@host = http://localhost:3000/api

## Recuperar todos los artículos
###
GET {{host}}/articles?page=1&limit=10
Content-Type: application/json

## Recuperar artículo por ID
###
GET {{host}}/articles/30001
Content-Type: application/json

##Buscar artículos
###
GET {{host}}/articles/search/rolex air
Content-Type: application/json

## Filtrar artículos
###
GET {{host}}/articles/filter?minPrice=100&maxPrice=3000&city=Madrid&shippingAvailable=true
Content-Type: application/json
@host = http://localhost:3000/api
@baseUrl = http://localhost:3000
@email = test.user@example.com
@password = secret123



## Recuperar todos los artículos
###
GET {{host}}/articles?page=1&limit=10
Content-Type: application/json

## Recuperar artículo por ID
###
GET {{host}}/articles/30001
Content-Type: application/json

##Buscar artículos
###
GET {{host}}/articles/search/rolex air
Content-Type: application/json

## Filtrar artículos
###
GET {{host}}/articles/filter?minPrice=100&maxPrice=3000&city=Madrid&shippingAvailable=true
Content-Type: application/json

### Crear anuncio
POST {{host}}/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImVtYWlsIjoidXN1YXJpby1jb211bjJAZ21haWwuY29tIiwicm9sIjoiVVNFUiIsImlhdCI6MTc4MjIzNzcwMCwiZXhwIjoxNzgyMzI0MTAwfQ.2SdLXoDY8VgvzF9haS7tNFLkSNUKFZseZFW-864585I
Content-Type: application/json

{
  "title": "Rolex Submariner Date",
  "description": "Rolex Submariner en muy buen estado. Revisión reciente.",
  "price": 11500,
  "condition": "VERY_GOOD",
  "year_of_manufacture": 2021,
  "case_material": "Acero inoxidable",
  "bracelet_material": "Acero inoxidable",
  "original_box": true,
  "original_papers": true,
  "shipping_available": true,
  "fk_styles_id": 1,
  "fk_models_id": 1,
  "publish": true,
  "images": [
    {
      "image_url": "https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/a677b2c664f6/catalogue/2026/upright-c/m126610lv-0002",
      "is_cover": true
    },
    {
      "image_url": "https://www.watchclub.com/upload/watches/originali/watch-club-rolex-submariner-date-126610lv-starbucksrolexwarranty-ref-126610lv-year-2021-15235-wb.png19.jpg"
    }
  ]
}

### Eliminar anuncio
DELETE {{host}}/articles/id
Authorization: Bearer `token`

### Editar anuncio
PUT {{host}}/articles/id
Authorization: Bearer `token`
Content-Type: application/json

{
  "title": "Audemars Piguet Royal Oak Offshore",
  "description": "Audemars Piguet Royal Oak Offshore en buen estado. Revisión reciente aceptable.",
  "price": 68000,
  "condition": "VERY_GOOD",
  "year_of_manufacture": 2024,
  "case_material": "Acero inoxidable",
  "bracelet_material": "Acero inoxidable",
  "original_box": true,
  "original_papers": false,
  "shipping_available": true,
  "fk_styles_id": 1,
  "fk_models_id": 1,
  "images": [
    {
      "image_url": "https://www.garciajoyeros.com/8757-thickbox_default/audemars-piguet-royal-oak-offshore.jpg",
      "is_cover": true
    },
    {
      "image_url": "https://www.uhrenworld.com/media/images/org/215004_1.jpg"
    },
    {
      "image_url": "https://res.cloudinary.com/wc-photo/image/upload/c_fill,w_3000,h_3000,g_auto/c_limit,w_2880/f_auto/q_auto/v1750417001/product/0b76a8cfc2050c5e459aed2aec089cc8/713ea787ca7b244c60ed38babcdb5cee?_a=BAVAfVDW0"
    }
  ]
}

### Marcar como vendido
PATCH {{host}}/articles/id/sold
Authorization: Bearer `token`
