@host = http://localhost:3000/api

# Auth
## Iniciar sesión
###
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "admin@atiempo.com",
    "password": "hashed_password_123"
}

# Artículos
## Recuperar todos los artículos
###
GET {{host}}/articles
Content-Type: application/json